spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: "sa"
    password:
    url: "jdbc:h2:tcp://localhost/~/test"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.checkin.CheckIn.domain
  mapper-locations: classpath:mapper/*.xml
