spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_ID}
    password: ${MYSQL_PW}
    url: "jdbc:mysql://localhost:3306/42checkin"
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop

