spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_ID}
    password: ${MYSQL_PW}
    url: "jdbc:mysql://localhost:3306/42checkin"
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.checkin.CheckIn.domain
  mapper-locations: classpath:mapper/*.xml

server:
  ssl:
    enabled: true
    key-alias: mykeysotre
    key-store: pkcsssl.pkcs12
    key-password: 11wjdghd
    key-store-password: 11wjdghd
    trust-store: mytrust.pkcs12
    trust-store-password: 11wjdghd
  port: 8443

