spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_ID}
    password: ${MYSQL_PW}
    url: "jdbc:mysql://localhost:3306/42checkin"
  sql:
    init:
      mode: always
      data-locations: classpath*:db/data.sql
      schema-locations: classpath*:db/schema.sql
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.checkin.CheckIn.domain
  mapper-locations: classpath:mapper/*.xml
